/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/income-screen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/my`; params?: Router.UnknownInputParams; } | { pathname: `/screens/splash-screen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Test`; params?: Router.UnknownInputParams; } | { pathname: `/screens/work-screen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/ChangePassword`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/OTPVerification`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/Register`; params?: Router.UnknownInputParams; } | { pathname: `/screens/chat`; params?: Router.UnknownInputParams; } | { pathname: `/screens/notification/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/current-shift`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/screens/schedule-detail/[bookingId]`, params: Router.UnknownInputParams & { bookingId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/income-screen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/my`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/splash-screen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Test`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/work-screen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/auth/ChangePassword`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/auth/ForgotPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/auth/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/auth/OTPVerification`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/auth/Register`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/notification/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/tabs/current-shift`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/tabs/home`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/tabs/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/tabs/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/schedule-detail/[bookingId]`, params: Router.UnknownOutputParams & { bookingId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens/income-screen${`?${string}` | `#${string}` | ''}` | `/screens/my${`?${string}` | `#${string}` | ''}` | `/screens/splash-screen${`?${string}` | `#${string}` | ''}` | `/screens/Test${`?${string}` | `#${string}` | ''}` | `/screens/work-screen${`?${string}` | `#${string}` | ''}` | `/screens/auth/ChangePassword${`?${string}` | `#${string}` | ''}` | `/screens/auth/ForgotPassword${`?${string}` | `#${string}` | ''}` | `/screens/auth/Login${`?${string}` | `#${string}` | ''}` | `/screens/auth/OTPVerification${`?${string}` | `#${string}` | ''}` | `/screens/auth/Register${`?${string}` | `#${string}` | ''}` | `/screens/chat${`?${string}` | `#${string}` | ''}` | `/screens/notification/notifications${`?${string}` | `#${string}` | ''}` | `/screens/tabs/current-shift${`?${string}` | `#${string}` | ''}` | `/screens/tabs/home${`?${string}` | `#${string}` | ''}` | `/screens/tabs/profile${`?${string}` | `#${string}` | ''}` | `/screens/tabs/schedule${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/income-screen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/my`; params?: Router.UnknownInputParams; } | { pathname: `/screens/splash-screen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Test`; params?: Router.UnknownInputParams; } | { pathname: `/screens/work-screen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/ChangePassword`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/OTPVerification`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/Register`; params?: Router.UnknownInputParams; } | { pathname: `/screens/chat`; params?: Router.UnknownInputParams; } | { pathname: `/screens/notification/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/current-shift`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/schedule`; params?: Router.UnknownInputParams; } | `/screens/schedule-detail/${Router.SingleRoutePart<T>}` | { pathname: `/screens/schedule-detail/[bookingId]`, params: Router.UnknownInputParams & { bookingId: string | number; } };
    }
  }
}
